baseURL: 'https://ca2didi.xyz/'
languageCode: 'zh'
defaultcontentlanguage: "zh"
title: 'Ca2D Pages'
theme: "PaperMod"
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Ca2D Pages"
  description: "Pages to log my coding life and leisure life"
  keywords: [Blog, Portfolio, PaperMod]
  author: Ca2didi
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2006/1/2" # "January 2, 2006" 
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  label:
    text: "Ca2D Pages"

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: "张修睿Ca2didi"
    subtitle: "这里是上面这个人的网站"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "Is this my head?"
    buttons:
      - name: 帖子
        url: posts
      - name: 标签
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi There! \U0001F44B"
    Content: "欢迎来到Ca2didi的博客。本人主要关注游戏客户端方向（目前做Unity为主）。"

  socialIcons:
    - name: twitter
      url: "https://twitter.com/Ca2didi"
    - name: github
      url: "https://github.com/Cardidi"
    - name: bilibili
      url: "https://space.bilibili.com/5367789"  
    - name: email
      url: "mailto:cardidi@live.cn"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/Cardidi/my-page/content"
    Text: "在 Github 上查看原Markdown" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: categories
      name: "分类"
      url: /categories/
      weight: 10
    - identifier: tags
      name: "标签"
      url: /tags/
      weight: 20
    - identifier: comet_studio
      name: "彗星工作室"
      url: "https://comet.studio"
      weight: 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai